version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=bff
    command: postgres -c 'max_connections=250'
    ports:
      - "5432:5432"
    volumes:
      - ./internal/infra/database/schema.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "400MB"