// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Endpoint struct {
	ID           uuid.UUID
	ServiceName  string
	Name         string
	Description  string
	Method       string
	Url          string
	Path         string
	Headers      string
	Body         string
	SensitiveApi bool
	Active       bool
	DeletedAt    sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
